name: 'CI'

on:
  workflow_dispatch:
  push:
    paths:
      - 'pyjaws/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'husk/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Tox
        run: pip install tox
      - name: Fix with Black
        run: tox -e fix
      - name: Lint with Ruff
        run: tox -e lint
      - name: Unit Testing
        id: tox
        working-directory: pyjaws
        run: tox